DATA:
  name: "CIFAR10"
  img_size: 32
  num_classes: 10
MODEL:
  backbone: "deep_conv"
  g_conv_dim: "N/A"
  d_conv_dim: "N/A"
OPTIMIZATION:
  d_updates_per_step: 2
  total_steps: 200000
  type_: "AdaBound"
  final_lr: 0.02
  gamma: 0.001
  eps: 0.00000001

